from app.models import BriefingInput, Signal


SAMPLE_BRIEFINGS: list[BriefingInput] = [
    BriefingInput(
        briefing_id="briefing-northstar-q2",
        account_name="Northstar Holdings",
        audience="executive",
        time_horizon="monthly",
        signals=[
            Signal(
                signal_id="rev-pipeline-01",
                domain="revenue",
                title="Pipeline coverage compression",
                metric="coverage",
                current_value=2.1,
                previous_value=2.8,
                target_value=3.0,
                impact_weight=0.92,
                confidence=0.86,
                owner="Revenue Operations",
                due_in_days=9,
                note="Enterprise segment slipped below planning guardrail.",
            ),
            Signal(
                signal_id="growth-exp-02",
                domain="growth",
                title="Pricing test lift remains durable",
                metric="qualified-conversion-lift",
                current_value=4.8,
                previous_value=4.4,
                target_value=3.5,
                impact_weight=0.74,
                confidence=0.81,
                owner="Growth PM",
                due_in_days=6,
                note="Higher-value framing is improving expansion intent.",
            ),
            Signal(
                signal_id="ai-run-03",
                domain="ai",
                title="Prompt fallback rate elevated",
                metric="fallback-rate",
                current_value=12.0,
                previous_value=7.0,
                target_value=5.0,
                impact_weight=0.63,
                confidence=0.79,
                owner="AI Platform",
                due_in_days=4,
                note="Guardrail-safe reroutes are masking latency debt.",
            ),
            Signal(
                signal_id="sec-identity-04",
                domain="security",
                title="Access review backlog growing",
                metric="open-reviews",
                current_value=41.0,
                previous_value=29.0,
                target_value=20.0,
                impact_weight=0.69,
                confidence=0.9,
                owner="Security Operations",
                due_in_days=11,
                note="Remediation delays are starting to hit customer-facing teams.",
            ),
        ],
    ),
    BriefingInput(
        briefing_id="briefing-atlas-board",
        account_name="Atlas Commerce",
        audience="board",
        time_horizon="quarterly",
        signals=[
            Signal(
                signal_id="cust-retain-01",
                domain="customer",
                title="Renewal confidence slipped in top cohort",
                metric="renewal-confidence",
                current_value=63.0,
                previous_value=71.0,
                target_value=80.0,
                impact_weight=0.88,
                confidence=0.84,
                owner="Customer Success",
                due_in_days=14,
                note="Trust and adoption pressure are converging near renewal.",
            ),
            Signal(
                signal_id="ops-workflow-02",
                domain="ops",
                title="Approval queue time improved",
                metric="queue-hours",
                current_value=18.0,
                previous_value=27.0,
                target_value=20.0,
                impact_weight=0.44,
                confidence=0.78,
                owner="Operations",
                due_in_days=10,
                note="Routing automation is reducing coordination drag.",
            ),
            Signal(
                signal_id="revenue-forecast-03",
                domain="revenue",
                title="Commit risk elevated in EMEA",
                metric="commit-risk",
                current_value=37.0,
                previous_value=25.0,
                target_value=18.0,
                impact_weight=0.81,
                confidence=0.82,
                owner="Sales Leadership",
                due_in_days=7,
                note="Forecast quality dropped as procurement cycles lengthened.",
            ),
        ],
    ),
]

